/**
 * 図鑑（用語カード）。ステージをクリアすると、そのステージの用語が入る（stages.ts の terms）。
 */
import type { GlyphId } from "./glyphs";

export type Term = {
  id: string;
  name: string;
  en: string;
  icon: GlyphId;
  /** ひとことで */
  short: string;
  body: string;
  analogy?: string;
  /** 本物では */
  real?: string;
};

export const TERMS: Term[] = [
  {
    id: "request",
    name: "リクエスト／レスポンス",
    en: "Request / Response",
    icon: "user",
    short: "スマホからの「お願い」と、サーバーからの「返事」",
    body: "ページを開く・ボタンを押すたびに、スマホ（ブラウザやアプリ）はサーバーへリクエストを送ります。サーバーは仕事をして、結果をレスポンスとして返します。Web のやりとりは、ほぼすべてこの往復でできています。",
    analogy: "注文すると、料理が出てくる",
    real: "HTTP（ブラウザとサーバーが話すときの決まりごと）",
  },
  {
    id: "server",
    name: "サーバー",
    en: "Server",
    icon: "app",
    short: "お願いを受けて仕事をし、返事をするコンピューター",
    body: "ページを組み立てたり、データを読み書きしたりします。データセンターで24時間動いていて、最近はクラウドで必要な分だけ借りるのが一般的です。",
    analogy: "お店の店員さん",
    real: "AWS（EC2）、Google Cloud、Vercel など",
  },
  {
    id: "ip",
    name: "IPアドレス",
    en: "IP Address",
    icon: "dns",
    short: "ネットの上の住所（203.0.113.10 のような番号）",
    body: "ネットにつながる機械には、それぞれ番号の住所があります。データはこの住所をあてにして届けられます。番号が足りなくなってきたため、もっと長い IPv6 も使われています。",
    analogy: "家の住所",
    real: "IPv4（203.0.113.10）、IPv6（2001:db8::1）",
  },
  {
    id: "domain",
    name: "ドメイン",
    en: "Domain Name",
    icon: "dns",
    short: "「odekake.app」のような、人が覚えやすい名前",
    body: "番号の住所は覚えにくいので、名前をつけて使います。ドメインは登録して、自分だけの名前として使えます。",
    analogy: "お店の名前（屋号）",
    real: "example.com、〇〇.jp など",
  },
  {
    id: "dns",
    name: "DNS",
    en: "Domain Name System",
    icon: "dns",
    short: "ドメインを IPアドレスに変える「ネットの電話帳」",
    body: "ブラウザはまず DNS に「この名前の住所は？」と問い合わせ、返ってきた IPアドレスへアクセスします。世界中の DNS サーバーが手分けして、名前と住所の対応を管理しています。",
    analogy: "電話帳",
    real: "Amazon Route 53、Cloudflare DNS など",
  },
  {
    id: "ttl",
    name: "TTL",
    en: "Time To Live",
    icon: "dns",
    short: "答えを覚えておいてよい時間",
    body: "DNS の答えには「何秒なら覚えておいてよいか」がついています。長くすると問い合わせが減って速くなりますが、住所を変えたときに、みんなに伝わるまで時間がかかります。",
    analogy: "「1時間は、この住所でOK」のメモ",
  },
  {
    id: "lb",
    name: "ロードバランサー",
    en: "Load Balancer",
    icon: "lb",
    short: "アクセスを、何台かのサーバーへ振り分ける係",
    body: "すいているサーバーへ送ったり、順番に送ったりして、負荷（ロード）を平らにならします（バランス）。止まったサーバーには送らないので、故障にも強くなります。",
    analogy: "お店の受付係",
    real: "AWS の ELB（ALB）、nginx など",
  },
  {
    id: "scale",
    name: "スケールアップ／アウト",
    en: "Scale Up / Scale Out",
    icon: "app",
    short: "1台を大きくするか、台数を増やすか",
    body: "スケールアップは1台を高性能にする方法。手軽ですが値段が上がりやすく、大きさに上限があります。スケールアウトは台数を増やす方法で、ロードバランサーと組み合わせれば、ずっと増やしていけます。",
    analogy: "すごい店員さん1人か、店員さんを増やすか",
  },
  {
    id: "status",
    name: "エラーの番号（503・504）",
    en: "HTTP Status Code",
    icon: "app",
    short: "返事についてくる「結果の番号」",
    body: "200 は成功、404 は見つからない、503 は混雑などで受けられない、504 は時間切れ（タイムアウト）。番号を見ると、どこで何が起きたかの手がかりになります。",
    analogy: "「ただいま混雑中」の札",
  },
  {
    id: "payg",
    name: "従量課金",
    en: "Pay as you go",
    icon: "app",
    short: "使った分だけ払うしくみ",
    body: "クラウドのサーバーは、動かした時間に応じてお金がかかります。混む時間だけ台数を増やし、すいたら減らす（オートスケール）と、むだなく運用できます。",
    analogy: "電気代・水道代",
  },
  {
    id: "db",
    name: "データベース",
    en: "Database",
    icon: "db",
    short: "データをまとめて、安全に保存する場所",
    body: "投稿・ユーザー・記録などを整理して保存し、さがしたり書きかえたりできるようにします。どのサーバーからも同じデータベースを見れば、データがバラバラになりません。",
    analogy: "お店の台帳",
    real: "PostgreSQL、MySQL（このアプリは PostgreSQL）",
  },
  {
    id: "stateless",
    name: "ステートレス",
    en: "Stateless",
    icon: "app",
    short: "サーバーが何も覚えておかない作り",
    body: "大事なデータはデータベースなどに置き、サーバーは毎回まっさらな状態で仕事をします。だから、どのサーバーに案内されても同じ結果になり、台数を増やしたり減らしたりしやすくなります。",
    analogy: "どの店員さんも、台帳を見て同じ対応",
  },
  {
    id: "cache",
    name: "キャッシュ",
    en: "Cache",
    icon: "cache",
    short: "よく使うデータを、すぐ出せる場所に置いておくこと",
    body: "データベースから読むより、メモリに置いたキャッシュから読むほうがずっと速いです。データが変わったときに、古いキャッシュを消す（更新する）のが、むずかしいところ。",
    analogy: "手元のメモ",
    real: "Redis、Memcached、ブラウザのキャッシュ",
  },
  {
    id: "hitrate",
    name: "ヒット率",
    en: "Hit Rate",
    icon: "cache",
    short: "キャッシュに、欲しいデータがあった割合",
    body: "ヒット率 90% なら、10回のうち9回はキャッシュだけで返せます。はじめはからっぽなので低く、使ううちに上がっていきます（ウォームアップ）。",
  },
  {
    id: "latency",
    name: "レイテンシ",
    en: "Latency",
    icon: "user",
    short: "お願いしてから、返事が届くまでの時間",
    body: "ms（ミリ秒＝1000分の1秒）で表します。往復の距離・待ち行列・処理の重さで長くなります。人は 0.1秒ほどの差でも「もっさり」を感じると言われます。",
    analogy: "注文してから、料理が出るまで",
  },
  {
    id: "cdn",
    name: "CDN",
    en: "Content Delivery Network",
    icon: "cdn",
    short: "各地の拠点から、ファイルを利用者の近くで配るしくみ",
    body: "画像・動画・プログラムのファイルなどを、世界中の拠点（エッジ）にコピーして置いておきます。近くから返すので速く、元のサーバーの仕事も減ります。",
    analogy: "近所の倉庫",
    real: "Amazon CloudFront、Cloudflare、Vercel など",
  },
  {
    id: "edge",
    name: "エッジ",
    en: "Edge",
    icon: "cdn",
    short: "利用者に近い「ふち」にある拠点",
    body: "CDN の拠点のように、ネットワークのはし（利用者のすぐ近く）にあるサーバーのこと。最近は、エッジでプログラムを動かすこともできます。",
  },
  {
    id: "redundancy",
    name: "冗長化",
    en: "Redundancy",
    icon: "app",
    short: "同じ役割のものを、いくつかそなえておくこと",
    body: "1台こわれても、残りが代わりに動けるようにします。サーバー・データベース・電源・回線など、あらゆるところで使われる考え方です。",
    analogy: "スペアキー",
  },
  {
    id: "spof",
    name: "単一障害点",
    en: "SPOF: Single Point of Failure",
    icon: "app",
    short: "そこが止まると、全体が止まる場所",
    body: "1台しかないサーバーやデータベースは、単一障害点です。構成図を見て「ここが止まったら？」と考えるのが、インフラ設計の基本です。",
  },
  {
    id: "healthcheck",
    name: "ヘルスチェック",
    en: "Health Check",
    icon: "lb",
    short: "定期的に「げんき？」と様子を確かめること",
    body: "ロードバランサーは、各サーバーへ定期的に確認のアクセスを送ります。返事がないサーバーは振り分け先から外し、回復したらもどします。",
    analogy: "朝の点呼",
  },
  {
    id: "failover",
    name: "フェイルオーバー",
    en: "Failover",
    icon: "replica",
    short: "故障したら、予備に自動で切りかえること",
    body: "本番のデータベースが止まったとき、予備（レプリカ）を本番に昇格させて仕事を続けます。切りかわるまでの数秒は、エラーになることがあります。",
  },
  {
    id: "replication",
    name: "レプリケーション",
    en: "Replication",
    icon: "replica",
    short: "データを別の場所へ、いつも写しておくこと",
    body: "本番DB への書きこみを予備DB にも送って、同じ中身にしておきます。予備は読みこみを手伝ったり、故障のときに代わりになったりします。",
    analogy: "台帳の写し",
  },
  {
    id: "queue",
    name: "キュー",
    en: "Message Queue",
    icon: "queue",
    short: "仕事を、順番待ちの列に並べておくしくみ",
    body: "すぐ終わらない仕事をキューに入れておけば、受け付けだけしてすぐ返事できます。急に仕事が増えても、列にためて少しずつ片づけられます。",
    analogy: "整理券",
    real: "Amazon SQS、RabbitMQ など",
  },
  {
    id: "async",
    name: "非同期処理",
    en: "Asynchronous Processing",
    icon: "queue",
    short: "終わるのを待たずに、先に進むやり方",
    body: "「受け付けました、終わったら知らせます」というやり方です。写真の加工・メールの送信・集計など、時間のかかる仕事でよく使われます。",
    analogy: "クリーニング屋さん（あとで受けとる）",
  },
  {
    id: "worker",
    name: "ワーカー",
    en: "Worker",
    icon: "worker",
    short: "キューから仕事を受けとって、裏で処理する係",
    body: "利用者とは直接やりとりせず、たまった仕事を順番に片づけます。仕事がたまってきたら、ワーカーを増やして対応します。",
    analogy: "裏方さん",
  },
  {
    id: "waf",
    name: "WAF",
    en: "Web Application Firewall",
    icon: "waf",
    short: "Web へのあやしいアクセスを、見分けて止める",
    body: "攻撃によくある形のリクエストや、同じ相手からの異常に多いアクセスなどを、入口でブロックします。サーバーに届く前に止めるのがポイントです。",
    analogy: "入口の警備員",
    real: "AWS WAF、Cloudflare WAF など",
  },
  {
    id: "ddos",
    name: "DDoS攻撃",
    en: "Distributed Denial of Service",
    icon: "bot",
    short: "大量のアクセスで、サービスを止めようとする攻撃",
    body: "たくさんの機械から一斉にアクセスを送りつけ、サーバーを手いっぱいにして、本物の利用者が使えないようにします。WAF や CDN の守りの機能で、入口で受け止めます。",
  },
  {
    id: "architecture",
    name: "システム構成",
    en: "Architecture",
    icon: "lb",
    short: "パーツの組み合わせ方の設計図",
    body: "どのパーツを、何台、どうつなぐか。アクセスの量・速さ・お金・故障への強さのバランスを考えて決めます。正解はひとつではありません。",
    analogy: "お店の間取り図",
  },
];

export const termById = (id: string) => TERMS.find((t) => t.id === id);
